spark.jars                             /opt/jars/delta-spark_2.12-3.2.0.jar,/opt/jars/delta-storage-3.2.0.jar,/opt/jars/hadoop-aws-3.3.4.jar,/opt/jars/aws-java-sdk-bundle-1.12.262.jar
spark.driver.extraClassPath            /opt/jars/delta-spark_2.12-3.2.0.jar:/opt/jars/delta-storage-3.2.0.jar:/opt/jars/hadoop-aws-3.3.4.jar:/opt/jars/aws-java-sdk-bundle-1.12.262.jar
spark.executor.extraClassPath          /opt/jars/delta-spark_2.12-3.2.0.jar:/opt/jars/delta-storage-3.2.0.jar:/opt/jars/hadoop-aws-3.3.4.jar:/opt/jars/aws-java-sdk-bundle-1.12.262.jar
spark.sql.extensions                   io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog        org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.hadoop.hive.metastore.uris       thrift://hive-metastore:9083
spark.hadoop.fs.s3a.endpoint           http://minio:9000
spark.hadoop.fs.s3a.access.key         minioadmin
spark.hadoop.fs.s3a.secret.key         minioadmin
spark.hadoop.fs.s3a.path.style.access  true
spark.sql.warehouse.dir                s3a://warehouse/
spark.extraListeners                   io.openlineage.spark.agent.OpenLineageSparkListener
spark.openlineage.transport.type       http
spark.openlineage.transport.url        http://marquez:5000
spark.openlineage.transport.endpoint   /api/v1/lineage
spark.openlineage.namespace            session_10
