spark.master=local[2]
spark.driver.memory=768m
spark.sql.shuffle.partitions=4
spark.default.parallelism=2
spark.sql.adaptive.enabled=true
spark.sql.session.timeZone=Asia/Ho_Chi_Minh
spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.polaris=org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.polaris.type=rest
spark.sql.catalog.polaris.uri=http://polaris:8181/api/catalog
spark.sql.catalog.polaris.warehouse=shopvn_catalog
spark.sql.catalog.polaris.token-refresh-enabled=false
spark.sql.catalog.polaris.scope=PRINCIPAL_ROLE:ALL
spark.sql.catalog.polaris.header.X-Iceberg-Access-Delegation=vended-credentials
spark.sql.catalog.polaris.credential=<POLARIS_CLIENT_ID>:<POLARIS_CLIENT_SECRET>
spark.sql.catalog.polaris.cache-enabled=true